### ISSUE TITLE
Cron $INSTANCE/manage.py generate_rights warnings

### ISSUE THREAD

**Issue by hydrandt** [modoboa/modoboa-radicale#5]
Hi, 

After update to latest version of modoboa-radicale (1.0.4), the cronjob that runs manage.py generate_rights every two minutes first gave us:

<pre>
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/models.py", line 10, in <module>
    from django.contrib.contenttypes import generic
ImportError: cannot import name generic
</pre>

and then after every run:

<pre>
System check identified some issues:

WARNINGS:
modoboa_amavis.Msgrcpt.mail: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
modoboa_amavis.Quarantine.mail: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
</pre>

Is it a bug, or have we done something wrong in the update process? I suppose this is not really important, is it a good idea to send the output of the cron to /dev/null, or is the warning easy to resolve?

Best,

Lukas

**Comment by tonioo** [comment]
There are two different issues in your description. The first one is problematic because it looks like you're using a Django (1.9.x) version not compatible with your modoboa version. Can you check that ? 

The second one is just a warning (unfortunately, I can't get rid of it) and you can ignore it by redirecting stdout to /dev/null.

**Comment by hydrandt** [comment]
Ah, I see. I suppose that this happened because I updated the modoboa package first, which caused Django to update to 1.9, and then waited a while before updating the radicale package - and the cron run in the meantime.

Ok, so if anyone gets the same warning, redirection of the cronjob stdout to /dev/null:

<pre>
vim /etc/cron.d/modoboa

and add &> /dev/null to the manage.py generate_rights line:

# Radicale rights file
*/2    *       *       *       *        root    $PYTHON $INSTANCE/manage.py generate_rights &> /dev/null
</pre>
